### ISSUE TITLE
Integrate this implementation in lottie xamarin

### ISSUE THREAD

**Issue by jzeferino** [azchohfi/LottieUWP#1]
@martijn00 created [LottieXamarin](https://github.com/martijn00/LottieXamarin) witch implements lottie for Android, iOS, MacOS and TvOS for Xamarin.

Would be great to have the UWP implementation added there.

What do you think @azchohfi ?

**Comment by azchohfi** [comment]
The second I pushed this I created the PR.
https://github.com/martijn00/LottieXamarin/pull/63
It has already been merged!

**Comment by JimSEOW** [comment]
@azchohfi  I could not wait so I compile and test the Example.Form.UWP.  Deploy, but no animaiton :-) 


Original in AnimationViewRenderer.cs in Lottie.Forms.UWP
`await _animationView.SetAnimationAsync(e.NewElement.Animation);`

However, in LottieUWP Sample
`await _animationView.SetAnimationAsync((string)e.NewElement.Animation);`

**Comment by azchohfi** [comment]
I created a sample to help understand how this should be used, but it's very similar to Android.

**Comment by JimSEOW** [comment]
@azchohfi I did a few days ago, just plug in a UWP project. No Animation. A while ago, I download the whole UWP_sample branch and compile the UWP. Again, no Animation. 

In both case, We see the slider, moving it does not lead to anything. 
Not sure WHY??
