### ISSUE TITLE
are these as performant as xaml controls?  ( not an issue )

### ISSUE THREAD

**Issue by touseefbsb** [azchohfi/LottieUWP#11]
I was just curious as wanted to ask can we and should we use these animations as part of any custom xaml controls or on our xaml pages just as clickable controls or stuff like that? I mean are these animation controls as performant as normal xaml controls? or is there is limit to how many animations should we use in 1 xaml page. the reason of this question is I can see a lot of animations which might be useful in usual uwp apps, like loading animations, hamburger icon animation and stuff like that.

**Comment by azchohfi** [comment]
I wouldn't use a lot of them in the same page, but it really depends on the animation. They should be very performant, and since they don't run on the UI thread, they wont play a part in the layout process, making them very light weight.
