### ISSUE TITLE
Support for Universal Windows 8.1

### ISSUE THREAD

**Issue by moamen-naanou** [azchohfi/LottieUWP#13]
I'm trying to use Lottie on UWP 8.1, but unfortunately it requires `Win2d.uwp ` which is not supported on this framework. Is there any other way to use `Win2d.win81` instead?

**Comment by azchohfi** [comment]
Unfortunately, this is not a scenario that we will support. If you want to, you can still fork the code and try to change the dependency to make this work, but I have no idea of how much effort that would take you.
