### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by corradocavalli** [azchohfi/LottieUWP#15]
A simple Lottie Animation uses about 3/4% of CPU increasing the number to 5 even with caching we reach more than 30%.
Is there a way to make CPU load smaller?

**Comment by azchohfi** [comment]
Only by reducing the FPS. The way the animations works is totally bound to the CPU(path calculation, progress and keyframes calculations, etc). There is work that can be done to cache some calculations, but not much.

**Comment by azchohfi** [comment]
I tried having this much CPU on a blank app with a gridview and LottieAnimationView, but I got 30% only with 100 animations on screen. It really will depend on the animation. And your CPU ;)

**Comment by azchohfi** [comment]
Version 2.5.0 (the one on NuGet) removed tons of memory leaks, so that should not be a problem anymore.

**Comment by azchohfi** [comment]
Have you tried the latest from MyGet? It should also fix the Speed on XAML.

**Comment by azchohfi** [comment]
I'm going to close this for now, since it's a hard thing to track and https://github.com/azchohfi/LottieUWP/commit/b4dc63209805eb2111b6e32053cfffc1c303194b probably helped a lot with CPU/GPU .

**Comment by corradocavalli** [comment]
Tested now, CPU load went to 40% to less than 2% with 5 animations, super well done!
