### ISSUE TITLE
Animations aren't playing when deployed to a console

### ISSUE THREAD

**Issue by mltejera** [azchohfi/LottieUWP#17]
It appears the animations aren't playing when the app is deployed to an Xbox console. We can 'progress through' the animation, but it's not playing smoothly 'hands off' like it does when deployed as a standard desktop UWP. Have we verified this use case works as anticipated?

**Comment by azchohfi** [comment]
It has not been tested, but it should.
Will setup environment to make some more testing.

**Comment by mltejera** [comment]
Awesome!

**Comment by azchohfi** [comment]
Unfortunately, I could replicate the problem. Still, I need to investigate more to find the real reason behind it.
Win2D should work just fine on Xbox, so it is probably something that LottieUWP is doing that it shouldn't.
