### ISSUE TITLE
Bezier curves are getting flattened

### ISSUE THREAD

**Issue by mltejera** [azchohfi/LottieUWP#18]
It appears LottieUWP is flattening bezier curves to be linear. We were able to verify that the iOS port maintained the curves and could find several references to 'bezier' in the source code. We have not had a chance to test the same animation in Android yet, but noted there was only 1 reference to 'bezier' in the Android code.

**Comment by azchohfi** [comment]
Could you send me a JSON file with the sample that is not working? If that is being achieved using expressions, than it wont work. Expressions are not supported.

**Comment by mltejera** [comment]
Talked to my motion designer - that animation did not use animations.

**Comment by azchohfi** [comment]
Fixed! Please test again using newest MyGet version.
