### ISSUE TITLE
Animation is not rendered initially when AutoPlay=False

### ISSUE THREAD

**Issue by jasonwurzel** [azchohfi/LottieUWP#26]
Hi, 

the following bug came when updating to the newest version of LottieUWP (2.5.0.365-beta)

When setting AutoPlay=False on LottieAnimationView, at first the view is totally blank. When triggering the animation once, it is subsequently drawn.
Steps to reproduce: 
- take the sample app
- set AutoPlay=False on LottieAnimationView in MainPage.xaml
- start sample app
=> animation is shown only when pressing the "Resume/Pause" button

greetings, 
Michael

**Comment by azchohfi** [comment]
Fixed.

**Comment by jasonwurzel** [comment]
Hi, thank you!
