### ISSUE TITLE
Xamarin Forms UWP Null Reference Exception On Navigation

### ISSUE THREAD

**Issue by MattRames** [azchohfi/LottieUWP#28]
When you navigate from a page playing an animation and go back to that page a null reference exception is thrown.

Com.Airbnb.Xamarin.Forms.Lottie: 2.5.1
LottieUWP: 2.5.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at LottieUWP.LottieDrawable.CanvasControlOnDraw(ICanvasAnimatedControl canvasControl, CanvasAnimatedDrawEventArgs args)

![51ec6be2-9c86-405a-80fa-d920c53630df](https://user-images.githubusercontent.com/9450530/37492806-b570fdb8-2870-11e8-84d0-5212579120b0.GIF)

Reproduction project: https://drive.google.com/file/d/184cMHR9icG2NfUvPIwnsKrRDaE6M-D8P/view?usp=sharing

**Comment by azchohfi** [comment]
Fixed by c84843ae0b3b67ed1d9e546b0b2141e932bd66cd.
