### ISSUE TITLE
Lottie animation disappears when set navigation cache mode enabled after navigate back

### ISSUE THREAD

**Issue by hupo376787** [azchohfi/LottieUWP#31]
Hi, I'm not sure its a bug, or do I need to set something to fix it right.

In my case, I have a MainPage, and another BlankPage. In MainPage, I have a lottie animation. When I navigate to BlankPage from MainPage, and then navigate back, lottie disappears.

See my git: https://github.com/hupo376787/LottieBugOrNot

![gif gif](https://user-images.githubusercontent.com/14960168/38170697-59ba07fc-35be-11e8-9cca-ba6a5cbc6560.gif)

**Comment by azchohfi** [comment]
I confirmed this as a bug. The internal composition is set to null when the component is unloaded (navigated away), so when you navigate back it will not draw anything.

**Comment by hupo376787** [comment]
If NavigationCache.Mode=Disabled, everything is ok

**Comment by azchohfi** [comment]
Yes. This is definitely a bug.

**Comment by Strypper** [comment]
Yes I have this bug too
