### ISSUE TITLE
Some crashes when compiled with Native tool chain

### ISSUE THREAD

**Issue by letsar** [azchohfi/LottieUWP#33]
When you compile an UWP app with .NET Native tool chain, some lottie files make the library to crash.
For example with the sample app in release mode:

1. Select **Assets\lottiefiles\gradient_animated_background.json**
2. Select another one
3. Wait one or two seconds => The app crash with the following exception: _System.Runtime.InteropServices.InvalidComObjectException: 'Excep_InvalidComObject_NoRCW_Wrapper. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485'_

Another example less explicit:
1. Select **Assets\lottiefiles\download.json**
2. Select another one
3. Wait one or two seconds => The app crash with the following exception: 
_Unhandled exception at 0x766C64A1 (combase.dll) in LottieUWP.Sample.exe: 0xC000027B_

**Comment by GitMoDu** [comment]
I know there are some serializers that don't like to be run in .Net Native. Is this the case?

**Comment by azchohfi** [comment]
@letsar Is this still happening on the latest version (2.6.1)?

**Comment by azchohfi** [comment]
I was able to simulate the bug and I think I caught them all. Let me know if you see this again.
