### ISSUE TITLE
Mobilo L.json final layer is identical to I.json

### ISSUE THREAD

**Issue by hermitdave** [azchohfi/LottieUWP#4]
I have tried both L.json from sample and the one in lottie android. Neither render correctly.

https://raw.githubusercontent.com/airbnb/lottie-android/master/LottieSample/src/main/assets/Mobilo/L.json

**Comment by azchohfi** [comment]
That's basically because masks are still not being rendered correctly. It is something that I'm aware of and tracking. I was focusing on using the composition APIs, and that is done now. I will try to tackle masks and mattes as a target for a 1st stable version.

**Comment by azchohfi** [comment]
Fixed by #38
