### ISSUE TITLE
Compilation warning: LottieAnimationView.Loop is obsolete

### ISSUE THREAD

**Issue by andrewdewaal** [azchohfi/LottieUWP#41]
Our project compiles to treat warnings as errors.
When compiling a project using a LottieAnimationView in a XAML view, the compiler shows the warning below:
![image](https://user-images.githubusercontent.com/6266242/44675112-8bad2380-a9fd-11e8-88e7-20639caee1b8.png)
This is reproducible using the sample project on this GitHub page by changing the project Debug settings to treat all warnings as errors.
The property in question is found in [LottieAnimationView, line 800](https://github.com/azchohfi/LottieUWP/blob/master/LottieUWP/LottieAnimationView.cs#L800).
The documentation for this property refers to the RepeatCount property; would it be feasible to remove usages of the Loop property and replace them with RepeatCount?
Many thanks!

**Comment by azchohfi** [comment]
Is there a reason why you are building from source? If you use the NuGet package (https://www.nuget.org/packages/LottieUWP) and don't use any of the deprecated methods, you shouldn't get any warning, and therefore any errors.

**Comment by andrewdewaal** [comment]
We originally tried with the NuGet package, and that was where we first encountered this.
The XAML for our test is as follows, using an animation from the sample project copied into our assets:
`                <lottieUwp:LottieAnimationView FileName="Assets/Lottie/the_final_frontier.json" />
`

We have no code-behind attached to this view for the LottieAnimationView; it is purely XAML.
Under these conditions, the warning is given at compile time.

**Comment by azchohfi** [comment]
I drilled down and this seems to be a problem with the generated code on XamlTypeInfo.g.cs. It is suppressing the warning only at Level0. For now, the only thing that can be done is either reducing the error level to 0, or manually suppressing 0612 for the project. I know it's not ideal... I will remove that property on a future version.

**Comment by azchohfi** [comment]
Ok, so I drilled with the responsible team for the XAML Markup Compiler and it seems that this bug only happens if the ObsoleteAttribute is used with the default message(i.e. [Obsolete], instead of [Obsolete("...")] ). I'm going to push this workaround for now, and they've already opened a bug internally to fix this for a future version of VS.

**Comment by andrewdewaal** [comment]
@azchohfi Excellent, thanks very much for the quick response and fix!
Is there a time frame in which this change would be pushed as an update to the NuGet package?
