### ISSUE TITLE
Build error was happen on LottieUWP 2.6.1

### ISSUE THREAD

**Issue by Daeho-Song** [azchohfi/LottieUWP#45]
Hello.

I have a question. I happen build error on LottieUWP 2.6.1

[LottieUWP\LottieCompositionFactory.cs]
312 : return await _taskCache[cacheKey].AsAsyncOperation().AsTask(cancellationToken);
320 : await task.AsAsyncOperation().AsTask(cancellationToken);

AsAsyncOperation is not defined in System.Threading.Tasks.Task.

How can I fix this error?

Thanks.

**Comment by azchohfi** [comment]
Which version of VS? Do you have the SDKs installed? It is building on the build server it has to be something on your machine. Have you tried a different one?

**Comment by azchohfi** [comment]
Let me know if the issue is still happening, but I could not simmulate.
