### ISSUE TITLE
.Net Standard Compatibility

### ISSUE THREAD

**Issue by azchohfi** [azchohfi/LottieUWP#6]
Needs to be fixed.

**Comment by azchohfi** [comment]
Actually, this is a problem with the Xamarin.Forms package. For some reason, the package uploaded to NuGet is not adding the dependency to LottieUWP, causing a "Could not load file or assembly 'LottieUWP'..." exception on runtime.

**Comment by chrisgate** [comment]
So what's d solution...can we install it manually since it's not from xamarin and u?

**Comment by azchohfi** [comment]
Just manually install it and you should be fine.

**Comment by chrisgate** [comment]
that i dont know how to do...........where can i download it ............from mynuget or where...........manual u mean i will do some command right? is it from package manager console ?

**Comment by azchohfi** [comment]
If you are getting the "Could not load file or assembly 'LottieUWP'..." exception on runtime when using the Lottie Xamarin.Forms, on a UWP project, just add the LottieUWP NuGet package reference (from the official nuget.org, no need to use the MyGet) to your UWP project.
That's not the problem you are trying to solve?

**Comment by azchohfi** [comment]
Closing this since it will be done by https://github.com/martijn00/LottieXamarin/pull/137
