### ISSUE TITLE
Is this repo moved to windows toolkit?

### ISSUE THREAD

**Issue by Panda-Sharp** [azchohfi/LottieUWP#62]
Is this repo still maintained and updated or is it moved to
https://github.com/windows-toolkit/Lottie-Windows
?

**Comment by azchohfi** [comment]
It's not the same repo. It's a from-the-ground-up new solution (much better and more performant). You should migrate your code to use that new implementation. This repo is no longer maintained, in favor to that solution.

**Comment by crutkas** [comment]
maybe a good idea would be updating your readme here and point to the new solution?

**Comment by azchohfi** [comment]
@sohchatt sent a PR a while ago adding a reference to it:
https://github.com/azchohfi/LottieUWP#lottieuwp

> For the official Lottie-Windows project, go here: https://aka.ms/lottie

**Comment by crutkas** [comment]
I would suggest having something much stronger.  It is not clear this is no longer maintained here and they should go to the Toolkit's implementation

> @sohchatt sent a PR a while ago adding a reference to it:
> https://github.com/azchohfi/LottieUWP#lottieuwp
> 
> > For the official Lottie-Windows project, go here: https://aka.ms/lottie

**Comment by sohchatt** [comment]
In keeping with @crutkas 's suggestion, do you want to include a soft-deprecation message or something similar?
